# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-09-08 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('catchPhrase', models.CharField(max_length=125)),
                ('bs', models.CharField(max_length=125)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=125)),
                ('ing', models.CharField(max_length=125)),
                ('geo', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='posts.Address')),
            ],
        ),
    ]
